version: '3'
services:
  golang:
    build: ./
    image: aikan/golang:0.2
    container_name: goback
    restart: always
    ports:
      - "18888:18888"
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
    external: true