version: '3'
services:
  golang:
    build: ./
    image: aikan/golang:1.0
    container_name: goback
    restart: always
    ports:
      - "18888:18888"
    networks:
      - one

networks:
  one:
    driver: bridge
    external: true