version: '3'
services:
  golang:
    build: ./
    image: aikan/golang:0.1
    container_name: goback
    restart: always
    environment:
      MYSQL_DSN: "root:aikan_root_980002_admin_007@tcp/aikan?charset=utf8&parseTime=True&loc=Local"
    ports:
      - "18888:18888"
    links:
      - mysql
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aikan_root_980002_admin_007
      MYSQL_DATABASE: aikan
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - /usr/local/redis:/usr/local/redis
    ports:
    - "6379:6379"

networks:
  test-net:
    driver: bridge