# 服务器端口，不写则是默认8080
server:
  port: 18888

# 数据库配置信息
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: aikan
  username: root
  password: aikan_root_980002_admin
  charset: utf8
  loc: Asia/Shanghai
redis:
  host: 23.94.201.38
  port: 6379
  password: redis_007

# 邮件发送配置
email:
  username: yassus@foxmail.com
  password: hiermcvuwdfobiec