# 服务器端口，不写则是默认8080
server:
  port: 18888

# 数据库配置信息
datasource:
  driverName: mysql
  host: 74.48.75.174
  #  host: 127.0.0.1
  port: 3306
  database: one
  username: root
  password: OwKO8HuAr0
  charset: utf8
  loc: Asia/Shanghai

redis:
  host: 74.48.75.174
  #  host: 127.0.0.1
  port: 6379
  password: 9RKWDsT6gm

mongo:
  host: 74.48.75.174
  #  host: 127.0.0.1
  port: 27017
  username: root
  password: yO08ZnSHHq

# 邮件发送配置
email:
  username: yassus@foxmail.com
  password: hiermcvuwdfobiec